### PR TITLE
fix: return absolute paths if one of the globs is absolute

### PR DESCRIPTION
**Pull request by brillout**
Proposal for #6.

### CODE REVIEW

**Comment by brillout** [comment]
I'll add docs to the readme if we end up merging this.

**Comment by brillout** [comment]
I updated the PR to remove the `filePathsRelativeToRoot` option.

I don't see a use case for configuring this.

Also, the user can always change the glob to fit what he wants:

```js
// If the user wants the file paths to be relative to root:
import.meta.importGlob('/path/to/*.js')
// Post-transform
{ "/path/to/some.js": () => import(/* ... */) }

// If the user wants the file paths to be relative to `__dirname`:
import.meta.importGlob('../../path/to/*.js')
// Post-transform
{ "../../path/to/some.js": () => import(/* ... */) }
```

**Comment by antfu** [comment]
BTW, we have this https://github.com/vitejs/vite/pull/6526 in Vite, which I haven't implemented in this plugin. Are you aware of it, and what do you think how it should affects this implementation

**Comment by antfu** [comment]
For multiple globs, do you think it makes sense for us to return to the absolute path if only the glob is absolute?

```ts
import.meta.importGlob(['/path/to/*.js', './*.ts')
// -->
{ 
  "/path/to/some.js": () => import(/* ... */),
  "/src/foo.ts": () => import(/* ... */)
}
```

**Comment by brillout** [comment]
> For multiple globs, do you think it makes sense for us to return the absolute paths if one of the globs is absolute?
> 
> ```ts
> import.meta.importGlob(['/path/to/*.js', './*.ts')
> // -->
> { 
>   "/path/to/some.js": () => import(/* ... */),
>   "/src/foo.ts": () => import(/* ... */)
> }
> ```

I'm not super happy about this, but I don't see an alternative.

**Comment by brillout** [comment]
> BTW, we have this [vitejs/vite#6526](https://github.com/vitejs/vite/pull/6526) in Vite, which I haven't implemented in this plugin. Are you aware of it, and what do you think how it should affects this implementation

👍. I'd say: it's a nice-to-have we can implement later.

I'd propose to get `vite-plugin-glob` out to more users, experiment, then we can see how/if we want to implement such nice-to-haves.

**Comment by antfu** [comment]
I will make a tweet later :)

**Comment by brillout** [comment]
Exciting 😀.

Btw, I'm going to release the new vps major `0.4.0` as soon as we merge the file extension restoration thing. (It's the only blocker for vps.)

**Pull request merged**
