### PR TITLE
feat: file extension restoration

### PR DESCRIPTION
**Pull request by brillout**
Edit by @antfu:

This PR introduces an experimental behavior that will append `lang.(ext)` when `query` is specified to keep the following plugins pipeline to process as the same file type.

---

I guess you feel like `queryRestoreFileExtension` is too long? :-)

### CODE REVIEW

**Comment by antfu** [comment]
Similar to https://github.com/antfu/vite-plugin-glob/pull/9#discussion_r838163232

Since the `query` option supports string, I guess you can reuse it by `{ query: 'foo=bar&lang.ts' }`? We could make the `?used` been injected before user-provided instead after to support this usage.

**Comment by antfu** [comment]
Similar to https://github.com/antfu/vite-plugin-glob/pull/9#discussion_r838163232

Since the `query` option supports string, I guess you can reuse it by `{ query: 'foo=bar&lang.ts' }`? We could make the `?used` been injected before user-provided instead after to support this usage.

**Comment by brillout** [comment]
It's not possible to use `query` for this, e.g.:

```js
// This is the actual glob used by vps (vite-plugin-ssr)
import.meta.glob('/**/*.page.*([a-zA-Z0-9])', { query: 'extractExportNames', queryRestoreFileExtension: true })
// Post-transform for a Vue app
{
  '/pages/hello.page.vue': () => import('../../examples/vue/pages/hello.page.vue?extractExportNames&lang.vue')
}
// Post-transform for a React app
{
  '/pages/hello.page.jsx': () => import('../../examples/react/pages/hello.page.jsx?extractExportNames&lang.jsx')
}
```

vps doesn't know the file extension of the files.

So file extension restoration needs to be done by `vite-plugin-glob`.

vps cannot use `vite-plugin-glob` without this option, and in general if we allow custom queries, then `vite-plugin-glob` should support file extension restoration.

> in Vite, our philosophy to the options is to keep them as minimal as possible

Makes sense & I like it. I'm thinking maybe we can simply always restore the file extension. I propose the following plan:
 - We always restore the file extension (we don't add an option `queryRestoreFileExtension`).
 - We let more users use `vite-plugin-glob` and see how it works out for users.
 - If the file extension restoration causes problems to users, only then do we consider adding an option like `skipFileExtensionRestoration`.

**Comment by antfu** [comment]
> We always restore the file extension

Tho I personally feel it might be a bit implicitly, I am happy to experiment with it and see how it works.

WDYT @patak-dev?

**Comment by brillout** [comment]
PR updated: file extension restoration is now automatic.

**Comment by antfu** [comment]
@brillout We are preparing to migrate this plugin for Vite v3. After the team discussion, we think this feature might be a bit risky to enable by default due to the implicitness. We planned to introduce it as an experimental flag (default false) in the first version of v3 and see the feedback. Thu in v0.3.0 of this plugin I also disabled it by default to prepare the migration, FYI.

**Comment by brillout** [comment]
Sounds like a solid plan. Thanks for the update.

(It was, btw., a lot of fun to do these vite-plugin-glob PRs :-).)

**Pull request merged**
